version: '3'

services:

  socialmedia:
    image: maven:3.5.3-jdk-10
    ports:
      - 8080
    working_dir: /app
    volumes:
      - ./pom.xml:/app/pom.xml
      - ./src:/app/src
      - ./target:/app/target
      - ./application.properties:/app/application.properties
    command: sh -c "java -jar /app/target/socialmedia.jar"
